### PR TITLE
Create CODEOWNERS

### PR DESCRIPTION
**Pull request by perk-sumo**

### CODE REVIEW

**Comment by JKashyap96** [comment]
@cullenlam-jask need for this.

**Comment by JKashyap96** [comment]
Hi @perk-sumo! Could you add this [team](https://github.com/orgs/SumoLogic/teams/sumoappdev) as an admin of this particular repo? I don't have the rights and Cullen might be busy.

**Comment by perk-sumo** [comment]
Sure thing - done :)

**Review by JKashyap96 — APPROVED** [review]
LGTM

**Pull request merged**
