### PR TITLE
Fix - bump jq install version to 2.2.1

### LINKED ISSUE #10: Bug: referenced version of jq/install dependency is broken
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Orb version

2.1.0

### Current behavior

The 2.2.0 version of `jq/install` that this orb depends on has a [breaking regression](https://github.com/CircleCI-Public/jq-orb/pull/31), and a fix has been released with [version 2.2.1](https://circleci.com/developer/orbs/orb/circleci/jq)

### Minimum reproduction config

Due to a breaking change in the dependency URL, all workflow runs will fail with an error message similar to:
```
Latest version of jq is jq-1.7
A different version of jq is installed (jq-1.6); removing it
curl: (3) URL using bad/illegal format or missing URL
```

### Other

_No response_

### PR DESCRIPTION
**Pull request by ezrapagel**
Update the version of [jq/install](https://circleci.com/developer/orbs/orb/circleci/jq) to the newest patch release at 2.2.1

Fixes #10

### CODE REVIEW

**Comment by JKashyap96** [comment]
Thanks @ezrapagel for raising this PR. Let me go through this and get back.

**Review by JKashyap96 — APPROVED** [review]
LGTM

**Comment by JKashyap96** [comment]
@ezrapagel Will be merging this post resolving an access issue.

**Comment by ezrapagel** [comment]
Thanks @JKashyap96. I'm not familiar with how the semver:patch gets bumped during the build. There's also a reference to version 2.1.0 in the README that will need to be updated to 2.1.1.

**Comment by ezrapagel** [comment]
Hey @JKashyap96, checking to see if there's an ETA for this. We've had to disable the `sumologic/workflow-collector` jobs for now and would like to turn those back on. Thanks

**Comment by JKashyap96** [comment]
@ezrapagel I would need GitHub org ownership to publish the new version of the orb. That is the issue I was talking about. ETA for this would be end of next week. I hope this helps. Will try for a quick release if possible before that. Thanks.

**Comment by JKashyap96** [comment]
@ezrapagel New Orb version of 2.1.1 has been released. You can turn on back the jobs now.

**Comment by ezrapagel** [comment]
Nice. Do you have any idea how long it'll take for the release to be in the CircleCI Orb Registry?
Thanks!

**Comment by ezrapagel** [comment]
Ah, nevermind, I see the 2.1.1 patch release 🎉. The README PR title has 2.2.1 btw.

**Pull request merged**
